#!/bin/bash

while IFS='' read -r line || [[ -n "$line" ]]; do
AR=$(echo $line | awk '{print $1}');
PAIR=$(echo $line | awk '{print $2}');
echo "Download $AR";

if [[ $PAIR == "PAIRED" ]]
then
	fastq-dump ${AR} --split-files --gzip 
else
	fastq-dump ${AR} --gzip
fi
done < $1
